version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_pop_covdischarged:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covdischarged
    outputs:
      highly_sensitive:
        cohort: output/input_covdischarged.csv

  generate_study_pop_covdischarged_csvt:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covdischarged_csvt
    outputs:
      highly_sensitive:
        cohort: output/input_covdischarged_csvt.csv

  generate_study_pop_pneum2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pneum2019
    outputs:
      highly_sensitive:
        cohort: output/input_pneum2019.csv

  generate_study_pop_flu2017_19:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flu2017_19_csvt
    outputs:
      highly_sensitive:
        cohort: output/input_flu2017_19_csvt.csv

  generate_study_pop_flu2017_19_csvt:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flu2017_19
    outputs:
      highly_sensitive:
        cohort: output/input_flu2017_19.csv

        
  generate_2019pool02:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool02
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool02.csv        

  generate_2019pool02_ALT:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019 --index-date-range "2019-02-01"
    outputs:
      highly_sensitive:
        cohort: output/input_2019_2019-02-01.csv        

  generate_2019pool03:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool03
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool03.csv        

  generate_2019pool04:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool04
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool04.csv        

  generate_2019pool05:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool05
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool05.csv        

  generate_2019pool06:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool06
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool06.csv        

  generate_2019pool07:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool07
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool07.csv        

  generate_2019pool08:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool08
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool08.csv        
           
  generate_2019pool09:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool09
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool09.csv        

  generate_2019pool10:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool10
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool10.csv        
      
  generate_2019pool11:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool11
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool11.csv        

  generate_2019pool12:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019pool12
    outputs:
      highly_sensitive:
        cohort: output/input_2019pool12.csv        
                   
  create_covid:
    run: stata-mp:latest analysis/cr_create_analysis_dataset.do COVID
    needs: [generate_study_pop_covdischarged]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_analysis_dataset_COVID.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset_COVID.log

  create_pneum2019:
    run: stata-mp:latest analysis/cr_create_analysis_dataset.do PNEUM 
    needs: [generate_study_pop_pneum2019]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_analysis_dataset_PNEUM.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset_PNEUM.log
 
  create_flu2017_19:
    run: stata-mp:latest analysis/cr_create_analysis_dataset.do FLU 
    needs: [generate_study_pop_flu2017_19]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_analysis_dataset_FLU.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset_FLU.log

  create_2019pool02:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 02
    needs: [generate_2019pool02]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_02.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_02.log

  create_2019pool03:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 03
    needs: [generate_2019pool03]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_03.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_03.log

  create_2019pool04:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 04
    needs: [generate_2019pool04]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_04.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_04.log

  create_2019pool05:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 05
    needs: [generate_2019pool05]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_05.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_05.log

  create_2019pool06:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 06
    needs: [generate_2019pool06]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_06.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_06.log

  create_2019pool07:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 07
    needs: [generate_2019pool07]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_07.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_07.log

  create_2019pool08:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 08
    needs: [generate_2019pool08]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_08.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_08.log

  create_2019pool09:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 09
    needs: [generate_2019pool09]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_09.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_09.log

  create_2019pool10:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 10
    needs: [generate_2019pool10]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_10.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_10.log

  create_2019pool11:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 11
    needs: [generate_2019pool11]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_11.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_11.log

  create_2019pool12:
    run: stata-mp:latest analysis/cr_create_2019pool_data.do 12
    needs: [generate_2019pool12]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_2019pool_data_12.dta
      moderately_sensitive:
        log: analysis/output/cr_create_2019pool_data_12.log


  getmatches2019:
    run: stata-mp:latest analysis/cr_getmatches2019.do
    needs:
      - create_covid
      - create_2019pool02
      - create_2019pool03
      - create_2019pool04
      - create_2019pool05
      - create_2019pool06
      - create_2019pool07
      - create_2019pool08
      - create_2019pool09
      - create_2019pool10
      - create_2019pool11
      - create_2019pool12
    outputs:
      highly_sensitive:
        cohort: analysis/cr_getmatches2019.dta
      moderately_sensitive:
        log: analysis/output/cr_getmatches2019.log

  appenddata:
    run: stata-mp:latest analysis/cr_append_process_data.do
    needs:
      - create_covid
      - create_pneum2019
      - create_flu2017_19
      - getmatches2019
    outputs:
      highly_sensitive:
        cohort: analysis/cr_append_process_data.dta
      moderately_sensitive:
        log: analysis/output/cr_append_process_data.log

  andescriptives_composites:
    run: stata-mp:latest analysis/model_descriptives_composites.do
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/*.log 
        tables: analysis/output/an_desc*.txt
        figures: analysis/output/an_cumulativeincidence*.svg
        timefig: analysis/output/an_desc*.svg
        models: analysis/output/models/an_cox*.ster

  ancrreg_flu1:
    run: stata-mp:latest analysis/an_crreg_outcome.do 1 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome1_cflu.log
        models: analysis/output/models/an_crreg_outcome1_cflu*.ster

  ancrreg_flu2:
    run: stata-mp:latest analysis/an_crreg_outcome.do 2 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome2_cflu.log
        models: analysis/output/models/an_crreg_outcome2_cflu*.ster

  ancrreg_flu3:
    run: stata-mp:latest analysis/an_crreg_outcome.do 3 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome3_cflu.log
        models: analysis/output/models/an_crreg_outcome3_cflu*.ster

  ancrreg_flu4:
    run: stata-mp:latest analysis/an_crreg_outcome.do 4 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome4_cflu.log
        models: analysis/output/models/an_crreg_outcome4_cflu*.ster

  ancrreg_flu5:
    run: stata-mp:latest analysis/an_crreg_outcome.do 5 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome5_cflu.log
        models: analysis/output/models/an_crreg_outcome5_cflu*.ster

  ancrreg_flu6:
    run: stata-mp:latest analysis/an_crreg_outcome.do 6 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome6_cflu.log
        models: analysis/output/models/an_crreg_outcome6_cflu*.ster

  ancrreg_flu7:
    run: stata-mp:latest analysis/an_crreg_outcome.do 7 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome7_cflu.log
        models: analysis/output/models/an_crreg_outcome7_cflu*.ster

  ancrreg_flu8:
    run: stata-mp:latest analysis/an_crreg_outcome.do 8 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome8_cflu.log
        models: analysis/output/models/an_crreg_outcome8_cflu*.ster

  ancrreg_flu9:
    run: stata-mp:latest analysis/an_crreg_outcome.do 9 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome9_cflu.log
        models: analysis/output/models/an_crreg_outcome9_cflu*.ster

  ancrreg_flu11:
    run: stata-mp:latest analysis/an_crreg_outcome.do 11 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome11_cflu.log
        models: analysis/output/models/an_crreg_outcome11_cflu*.ster

  ancrreg_flu12:
    run: stata-mp:latest analysis/an_crreg_outcome.do 12 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome12_cflu.log
        models: analysis/output/models/an_crreg_outcome12_cflu*.ster

  ancrreg_flu13:
    run: stata-mp:latest analysis/an_crreg_outcome.do 13 flu
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome13_cflu.log
        models: analysis/output/models/an_crreg_outcome13_cflu*.ster

  ancrreg_2019gp1:
    run: stata-mp:latest analysis/an_crreg_outcome.do 1 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome1_c2019gp.log
        models: analysis/output/models/an_crreg_outcome1_c2019gp*.ster

  ancrreg_2019gp2:
    run: stata-mp:latest analysis/an_crreg_outcome.do 2 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome2_c2019gp.log
        models: analysis/output/models/an_crreg_outcome2_c2019gp*.ster

  ancrreg_2019gp3:
    run: stata-mp:latest analysis/an_crreg_outcome.do 3 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome3_c2019gp.log
        models: analysis/output/models/an_crreg_outcome3_c2019gp*.ster

  ancrreg_2019gp4:
    run: stata-mp:latest analysis/an_crreg_outcome.do 4 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome4_c2019gp.log
        models: analysis/output/models/an_crreg_outcome4_c2019gp*.ster

  ancrreg_2019gp5:
    run: stata-mp:latest analysis/an_crreg_outcome.do 5 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome5_c2019gp.log
        models: analysis/output/models/an_crreg_outcome5_c2019gp*.ster

  ancrreg_2019gp6:
    run: stata-mp:latest analysis/an_crreg_outcome.do 6 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome6_c2019gp.log
        models: analysis/output/models/an_crreg_outcome6_c2019gp*.ster

  ancrreg_2019gp7:
    run: stata-mp:latest analysis/an_crreg_outcome.do 7 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome7_c2019gp.log
        models: analysis/output/models/an_crreg_outcome7_c2019gp*.ster

  ancrreg_2019gp8:
    run: stata-mp:latest analysis/an_crreg_outcome.do 8 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome8_c2019gp.log
        models: analysis/output/models/an_crreg_outcome8_c2019gp*.ster

  ancrreg_2019gp9:
    run: stata-mp:latest analysis/an_crreg_outcome.do 9 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome9_c2019gp.log
        models: analysis/output/models/an_crreg_outcome9_c2019gp*.ster

  ancrreg_2019gp11:
    run: stata-mp:latest analysis/an_crreg_outcome.do 11 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome11_c2019gp.log
        models: analysis/output/models/an_crreg_outcome11_c2019gp*.ster

  ancrreg_2019gp12:
    run: stata-mp:latest analysis/an_crreg_outcome.do 12 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome12_c2019gp.log
        models: analysis/output/models/an_crreg_outcome12_c2019gp*.ster

  ancrreg_2019gp13:
    run: stata-mp:latest analysis/an_crreg_outcome.do 13 2019gp
    needs: [appenddata]
    outputs:
      moderately_sensitive:
        logs: analysis/output/an_crreg_outcome13_c2019gp.log
        models: analysis/output/models/an_crreg_outcome13_c2019gp*.ster

  ancrforests:
    run: stata-mp:latest analysis/an_processout_regressionmodels_FOREST.do
    needs:
      - andescriptives_composites
      - ancrreg_flu1
      - ancrreg_flu2
      - ancrreg_flu3
      - ancrreg_flu4
      - ancrreg_flu5
      - ancrreg_flu6
      - ancrreg_flu7
      - ancrreg_flu8
      - ancrreg_flu9
      - ancrreg_flu11
      - ancrreg_flu12
      - ancrreg_flu13
      - ancrreg_2019gp1
      - ancrreg_2019gp2
      - ancrreg_2019gp3
      - ancrreg_2019gp4
      - ancrreg_2019gp5
      - ancrreg_2019gp6
      - ancrreg_2019gp7
      - ancrreg_2019gp8
      - ancrreg_2019gp9
      - ancrreg_2019gp11
      - ancrreg_2019gp12
      - ancrreg_2019gp13
    outputs:
      moderately_sensitive:
        graphs: analysis/output/an_processout_regressionmodels_FOREST*.svg       
      
  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_study_pop_covdischarged]
    outputs:
      moderately_sensitive:
        log: logs/model.log

