version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  create_dataset:
    run: stata-mp:latest analysis/cr_create_analysis_dataset.do 
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: analysis/cr_create_analysis_dataset.dta
      moderately_sensitive:
        log: analysis/output/cr_create_analysis_dataset.log

  run_model:
    run: stata-mp:latest analysis/model.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/model.log

